In [1]:
import pandas as pd

In [4]:
#TODO: re-run scGPT results
scgpt_metrics = pd.read_csv('/home/jupyter/sceval/analysis_uns/metrics_runs.csv')
# scgpt_metrics['method'] = 'scimiarity'
# scgpt_metrics['group'] = 'scimiarity'
scgpt_metrics = scgpt_metrics[scgpt_metrics['method'].isin(['scgpt','scgpt_cancer'])]
scgpt_metrics

,method,NMI_cluster/label,ARI_cluster/label,ASW_label,graph_conn,ASW_batch,ASW_label/batch,PCR_batch,avg_bio,group
20,scgpt,0.694494,0.699925,0.543034,0.983788,0.501380,0.907433,0.031992,0.645817,scgpt
21,scgpt,0.696455,0.710770,0.541832,0.970261,0.501530,0.907569,0.030317,0.649685,scgpt
22,scgpt,0.677054,0.621885,0.537469,0.963834,0.501291,0.935357,0.030894,0.612136,scgpt
23,scgpt,0.695442,0.695780,0.537064,0.985317,0.501059,0.928152,0.030208,0.642762,scgpt
24,scgpt,0.703970,0.652718,0.538642,0.970983,0.500504,0.936807,0.027519,0.631777,scgpt
25,scgpt,0.691655,0.647659,0.542064,0.974693,0.501382,0.930576,0.029883,0.627126,scgpt
26,scgpt,0.681078,0.675606,0.537629,0.964858,0.500409,0.935833,0.031891,0.631438,scgpt
27,scgpt,0.693984,0.685710,0.538299,0.978565,0.501516,0.923053,0.030655,0.639331,scgpt
28,scgpt,0.702780,0.708913,0.541008,0.961869,0.500777,0.915734,0.030209,0.650901,scgpt
29,scgpt,0.711292,0.674724,0.541395,0.956222,0.500455,0.919991,0.027509,0.642470,scgpt
30,scgpt_cancer,0.701323,0.709255,0.538142,0.982596,0.498208,0.927195,0.035944,0.649573,scgpt
31,scgpt_cancer,0.717824,0.722219,0.540023,0.968316,0.497077,0.887368,0.032614,0.660022,scgpt
32,scgpt_cancer,0.709907,0.708309,0.538711,0.973259,0.497071,0.916641,0.034489,0.652309,scgpt
33,scgpt_cancer,0.711817,0.731958,0.540058,0.986147,0.498392,0.921568,0.034424,0.661278,scgpt
34,scgpt_cancer,0.693981,0.663168,0.540692,0.983347,0.497030,0.905629,0.032863,0.632614,scgpt
35,scgpt_cancer,0.703092,0.720722,0.539723,0.982860,0.496949,0.926090,0.034146,0.654513,scgpt
36,scgpt_cancer,0.706388,0.678669,0.538861,0.985270,0.498618,0.926229,0.032668,0.641306,scgpt
37,scgpt_cancer,0.708675,0.691362,0.538976,0.977174,0.496543,0.915587,0.035662,0.646338,scgpt
38,scgpt_cancer,0.696593,0.690427,0.539011,0.974218,0.496126,0.933201,0.034994,0.642010,scgpt
39,scgpt_cancer,0.691642,0.649032,0.538903,0.985233,0.498838,0.934688,0.037537,0.626525,scgpt

In [2]:
_10_runs_df  = pd.read_csv('./metrics/metrics_10_runs.csv')
_10_runs_df

,method,NMI_cluster/label,ARI_cluster/label,ASW_label,graph_conn,ASW_batch,ASW_label/batch,PCR_batch,avg_bio,group
0,hvg,0.623929,0.504672,0.506691,0.977224,0.482762,0.939550,0.200379,0.545097,baseline
1,hvg,0.661756,0.637854,0.506394,0.987633,0.481334,0.947129,0.200692,0.602001,baseline
2,hvg,0.566944,0.304677,0.506617,0.986227,0.481981,0.942024,0.203416,0.459413,baseline
3,hvg,0.678981,0.600340,0.507554,0.985124,0.482889,0.945861,0.205707,0.595625,baseline
4,hvg,0.569790,0.291233,0.507050,0.988255,0.480763,0.944116,0.200572,0.456024,baseline
...,...,...,...,...,...,...,...,...,...,...
85,scfoundation,0.732734,0.641470,0.572355,0.988894,0.497585,0.931725,0.030870,0.648853,scFoundation
86,scfoundation,0.727844,0.647603,0.573923,0.992945,0.497462,0.932971,0.030373,0.649790,scFoundation
87,scfoundation,0.721546,0.620240,0.572846,0.992617,0.495873,0.916568,0.031855,0.638211,scFoundation
88,scfoundation,0.735540,0.647488,0.572648,0.984192,0.497757,0.882237,0.031219,0.651892,scFoundation
89,scfoundation,0.746754,0.666797,0.573666,0.990942,0.497456,0.915417,0.030131,0.662406,scFoundation

In [6]:
scimiarity_metrics = pd.read_csv('./metrics/scimiarity.csv')
scimiarity_metrics['method'] = 'scimiarity'
scimiarity_metrics['group'] = 'scimiarity'
scimiarity_metrics

,NMI_cluster/label,ARI_cluster/label,ASW_label,graph_conn,ASW_batch,ASW_label/batch,PCR_batch,avg_bio,method,group
0,0.744579,0.593142,0.660594,0.940631,0.500622,0.903169,0.025523,0.666105,scimiarity,scimiarity
1,0.736055,0.567434,0.659012,0.981589,0.500158,0.902207,0.023436,0.654167,scimiarity,scimiarity
2,0.757886,0.592463,0.660530,0.946523,0.498861,0.918133,0.024563,0.670293,scimiarity,scimiarity
3,0.759724,0.621653,0.661637,0.989618,0.499431,0.919936,0.022592,0.681004,scimiarity,scimiarity
4,0.754180,0.605643,0.662376,0.987431,0.499497,0.916954,0.024420,0.674066,scimiarity,scimiarity
5,0.751736,0.591089,0.659285,0.982938,0.498682,0.890817,0.021366,0.667370,scimiarity,scimiarity
6,0.745941,0.591193,0.657771,0.940666,0.499342,0.923520,0.023818,0.664968,scimiarity,scimiarity
7,0.734593,0.580973,0.660823,0.988149,0.499170,0.931770,0.023024,0.658796,scimiarity,scimiarity
8,0.768763,0.623870,0.663003,0.990565,0.499609,0.909882,0.022676,0.685212,scimiarity,scimiarity
9,0.759774,0.627816,0.661495,0.941153,0.499995,0.871146,0.024318,0.683028,scimiarity,scimiarity

In [7]:
cellplm_metrics = pd.read_csv('./metrics/cellplm.csv')
cellplm_metrics['method'] = 'cellplm'
cellplm_metrics['group'] = 'cellplm'
cellplm_metrics

,NMI_cluster/label,ARI_cluster/label,ASW_label,graph_conn,ASW_batch,ASW_label/batch,PCR_batch,avg_bio,method,group
0,0.555624,0.373994,0.618308,0.807329,0.491255,0.840414,0.019848,0.515975,cellplm,cellplm
1,0.564830,0.387498,0.618697,0.809863,0.492992,0.849901,0.019255,0.523675,cellplm,cellplm
2,0.563177,0.381643,0.617819,0.807086,0.492602,0.843725,0.021348,0.520880,cellplm,cellplm
3,0.560502,0.370177,0.613014,0.806663,0.492419,0.876036,0.017928,0.514564,cellplm,cellplm
4,0.561621,0.377208,0.614563,0.809469,0.492292,0.872457,0.021841,0.517798,cellplm,cellplm
5,0.561148,0.373930,0.617994,0.845114,0.492419,0.903610,0.020072,0.517690,cellplm,cellplm
6,0.559625,0.375534,0.616482,0.808181,0.492151,0.821193,0.022216,0.517214,cellplm,cellplm
7,0.560766,0.381815,0.616015,0.810473,0.492694,0.892457,0.021304,0.519532,cellplm,cellplm
8,0.551656,0.369464,0.615176,0.812285,0.493225,0.885528,0.019937,0.512098,cellplm,cellplm
9,0.563349,0.379399,0.616509,0.811370,0.491976,0.879568,0.021596,0.519752,cellplm,cellplm

In [8]:
_10_runs_df

,method,NMI_cluster/label,ARI_cluster/label,ASW_label,graph_conn,ASW_batch,ASW_label/batch,PCR_batch,avg_bio,group
0,hvg,0.623929,0.504672,0.506691,0.977224,0.482762,0.939550,0.200379,0.545097,baseline
1,hvg,0.661756,0.637854,0.506394,0.987633,0.481334,0.947129,0.200692,0.602001,baseline
2,hvg,0.566944,0.304677,0.506617,0.986227,0.481981,0.942024,0.203416,0.459413,baseline
3,hvg,0.678981,0.600340,0.507554,0.985124,0.482889,0.945861,0.205707,0.595625,baseline
4,hvg,0.569790,0.291233,0.507050,0.988255,0.480763,0.944116,0.200572,0.456024,baseline
...,...,...,...,...,...,...,...,...,...,...
85,scfoundation,0.732734,0.641470,0.572355,0.988894,0.497585,0.931725,0.030870,0.648853,scFoundation
86,scfoundation,0.727844,0.647603,0.573923,0.992945,0.497462,0.932971,0.030373,0.649790,scFoundation
87,scfoundation,0.721546,0.620240,0.572846,0.992617,0.495873,0.916568,0.031855,0.638211,scFoundation
88,scfoundation,0.735540,0.647488,0.572648,0.984192,0.497757,0.882237,0.031219,0.651892,scFoundation
89,scfoundation,0.746754,0.666797,0.573666,0.990942,0.497456,0.915417,0.030131,0.662406,scFoundation

In [9]:
combined_results = pd.concat([_10_runs_df, scimiarity_metrics, cellplm_metrics, scgpt_metrics], axis=0)

In [10]:
combined_results

,method,NMI_cluster/label,ARI_cluster/label,ASW_label,graph_conn,ASW_batch,ASW_label/batch,PCR_batch,avg_bio,group
0,hvg,0.623929,0.504672,0.506691,0.977224,0.482762,0.939550,0.200379,0.545097,baseline
1,hvg,0.661756,0.637854,0.506394,0.987633,0.481334,0.947129,0.200692,0.602001,baseline
2,hvg,0.566944,0.304677,0.506617,0.986227,0.481981,0.942024,0.203416,0.459413,baseline
3,hvg,0.678981,0.600340,0.507554,0.985124,0.482889,0.945861,0.205707,0.595625,baseline
4,hvg,0.569790,0.291233,0.507050,0.988255,0.480763,0.944116,0.200572,0.456024,baseline
...,...,...,...,...,...,...,...,...,...,...
35,scgpt_cancer,0.703092,0.720722,0.539723,0.982860,0.496949,0.926090,0.034146,0.654513,scgpt
36,scgpt_cancer,0.706388,0.678669,0.538861,0.985270,0.498618,0.926229,0.032668,0.641306,scgpt
37,scgpt_cancer,0.708675,0.691362,0.538976,0.977174,0.496543,0.915587,0.035662,0.646338,scgpt
38,scgpt_cancer,0.696593,0.690427,0.539011,0.974218,0.496126,0.933201,0.034994,0.642010,scgpt
39,scgpt_cancer,0.691642,0.649032,0.538903,0.985233,0.498838,0.934688,0.037537,0.626525,scgpt

In [11]:
combined_results.to_csv('./metrics/metrics_10_runs3.csv')